version: '3.7'

services:
    messenger:
        image: postgres
        ports:
            - '5432:5432'
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
